const Log = require('./log.js');
const DBManager = require('./DBManager.js');

let suported_game_types = [
	{"type" : "7d2d", "description" : "7 Days to Die (2013)"}, 
	{"type" : "ageofchivalry", "description" : "Age of Chivalry (2007)"}, 
	{"type" : "aoe2", "description" : "Age of Empires 2 (1999)"}, 
	{"type" : "alienarena", "description" : "Alien Arena (2004)"}, 
	{"type" : "alienswarm", "description" : "Alien Swarm (2010)"}, 
	{"type" : "avp2", "description" : "Aliens versus Predator 2 (2001)"}, 
	{"type" : "avp2010", "description" : "Aliens vs. Predator (2010)"}, 
	{"type" : "americasarmy", "description" : "America\\\'s Army (2002)"}, 
	{"type" : "americasarmy2", "description" : "America\\\'s Army 2 (2003)"}, 
	{"type" : "americasarmy3", "description" : "America\\\'s Army 3 (2009)"}, 
	{"type" : "americasarmypg", "description" : "America\\\'s Army: Proving Grounds (2015)"}, 
	{"type" : "arcasimracing", "description" : "Arca Sim Racing (2008)"}, 
	{"type" : "arkse", "description" : "Ark: Survival Evolved (2017)"}, 
	{"type" : "arma2", "description" : "ARMA 2 (2009)"}, 
	{"type" : "arma2oa", "description" : "ARMA 2: Operation Arrowhead (2010)"}, 
	{"type" : "arma3", "description" : "ARMA 3 (2013)"}, 
	{"type" : "arma", "description" : "ARMA: Armed Assault (2007)"}, 
	{"type" : "armacwa", "description" : "ARMA: Cold War Assault (2011)"}, 
	{"type" : "armar", "description" : "ARMA: Resistance (2011)"}, 
	{"type" : "armagetron", "description" : "Armagetron Advanced (2001)"}, 
	{"type" : "assettocorsa", "description" : "Assetto Corsa (2014)"}, 
	{"type" : "atlas", "description" : "Atlas (2018)"}, 
	{"type" : "baldursgate", "description" : "Baldur\\\'s Gate (1998)"}, 
	{"type" : "bat1944", "description" : "Battalion 1944 (2018)"}, 
	{"type" : "bf1942", "description" : "Battlefield 1942 (2002)"}, 
	{"type" : "bf2", "description" : "Battlefield 2 (2005)"}, 
	{"type" : "bf2142", "description" : "Battlefield 2142 (2006)"}, 
	{"type" : "bf3", "description" : "Battlefield 3 (2011)"}, 
	{"type" : "bf4", "description" : "Battlefield 4 (2013)"}, 
	{"type" : "bfh", "description" : "Battlefield Hardline (2015)"}, 
	{"type" : "bfv", "description" : "Battlefield Vietnam (2004)"}, 
	{"type" : "bfbc2", "description" : "Battlefield: Bad Company 2 (2010)"}, 
	{"type" : "breach", "description" : "Breach (2011)"}, 
	{"type" : "breed", "description" : "Breed (2004)"}, 
	{"type" : "brink", "description" : "Brink (2011)"}, 
	{"type" : "buildandshoot", "description" : "Build and Shoot / Ace of Spades Classic (2012)"}, 
	{"type" : "cod", "description" : "Call of Duty (2003)"}, 
	{"type" : "cod2", "description" : "Call of Duty 2 (2005)"}, 
	{"type" : "cod3", "description" : "Call of Duty 3 (2006)"}, 
	{"type" : "cod4", "description" : "Call of Duty 4: Modern Warfare (2007)"}, 
	{"type" : "codmw2", "description" : "Call of Duty: Modern Warfare 2 (2009)"}, 
	{"type" : "codmw3", "description" : "Call of Duty: Modern Warfare 3 (2011)"}, 
	{"type" : "coduo", "description" : "Call of Duty: United Offensive (2004)"}, 
	{"type" : "codwaw", "description" : "Call of Duty: World at War (2008)"}, 
	{"type" : "callofjuarez", "description" : "Call of Juarez (2006)"}, 
	{"type" : "chaser", "description" : "Chaser (2003)"}, 
	{"type" : "chrome", "description" : "Chrome (2003)"}, 
	{"type" : "codenameeagle", "description" : "Codename Eagle (2000)"}, 
	{"type" : "cacrenegade", "description" : "Command and Conquer: Renegade (2002)"}, 
	{"type" : "commandos3", "description" : "Commandos 3: Destination Berlin (2003)"}, 
	{"type" : "conanexiles", "description" : "Conan Exiles (2018)"}, 
	{"type" : "contagion", "description" : "Contagion (2011)"}, 
	{"type" : "contactjack", "description" : "Contract J.A.C.K. (2003)"}, 
	{"type" : "cs15", "description" : "Counter-Strike 1.5 (2002)"}, 
	{"type" : "cs16", "description" : "Counter-Strike 1.6 (2003)"}, 
	{"type" : "cs2d", "description" : "Counter-Strike: 2D (2004)"}, 
	{"type" : "cscz", "description" : "Counter-Strike: Condition Zero (2004)"}, 
	{"type" : "csgo", "description" : "Counter-Strike: Global Offensive (2012)"}, 
	{"type" : "css", "description" : "Counter-Strike: Source (2004)"}, 
	{"type" : "crossracing", "description" : "Cross Racing Championship Extreme 2005 (2005)"}, 
	{"type" : "crysis", "description" : "Crysis (2007)"}, 
	{"type" : "crysis2", "description" : "Crysis 2 (2011)"}, 
	{"type" : "crysiswars", "description" : "Crysis Wars (2008)"}, 
	{"type" : "daikatana", "description" : "Daikatana (2000)"}, 
	{"type" : "dnl", "description" : "Dark and Light (2017)"}, 
	{"type" : "dmomam", "description" : "Dark Messiah of Might and Magic (2006)"}, 
	{"type" : "darkesthour", "description" : "Darkest Hour: Europe \\\'44-\\\'45 (2008)"}, 
	{"type" : "dod", "description" : "Day of Defeat (2003)"}, 
	{"type" : "dods", "description" : "Day of Defeat: Source (2005)"}, 
	{"type" : "doi", "description" : "Day of Infamy (2017)"}, 
	{"type" : "daysofwar", "description" : "Days of War (2017)"}, 
	{"type" : "dayz", "description" : "DayZ (2018)"}, 
	{"type" : "dayzmod", "description" : "DayZ Mod (2013)"}, 
	{"type" : "deadlydozenpt", "description" : "Deadly Dozen: Pacific Theater (2002)"}, 
	{"type" : "dh2005", "description" : "Deer Hunter 2005 (2004)"}, 
	{"type" : "descent3", "description" : "Descent 3 (1999)"}, 
	{"type" : "deusex", "description" : "Deus Ex (2000)"}, 
	{"type" : "devastation", "description" : "Devastation (2003)"}, 
	{"type" : "dinodday", "description" : "Dino D-Day (2011)"}, 
	{"type" : "dirttrackracing2", "description" : "Dirt Track Racing 2 (2002)"}, 
	{"type" : "doom3", "description" : "Doom 3 (2004)"}, 
	{"type" : "dota2", "description" : "Dota 2 (2013)"}, 
	{"type" : "drakan", "description" : "Drakan: Order of the Flame (1999)"}, 
	{"type" : "empyrion", "description" : "Empyrion - Galactic Survival (2015)"}, 
	{"type" : "etqw", "description" : "Enemy Territory: Quake Wars (2007)"}, 
	{"type" : "fear", "description" : "F.E.A.R. (2005)"}, 
	{"type" : "f1c9902", "description" : "F1 Challenge \\\'99-\\\'02 (2002)"}, 
	{"type" : "farcry", "description" : "Far Cry (2004)"}, 
	{"type" : "farcry2", "description" : "Far Cry 2 (2008)"}, 
	{"type" : "f12002", "description" : "Formula One 2002 (2002)"}, 
	{"type" : "fortressforever", "description" : "Fortress Forever (2007)"}, 
	{"type" : "ffow", "description" : "Frontlines: Fuel of War (2008)"}, 
	{"type" : "garrysmod", "description" : "Garry\\\'s Mod (2004)"}, 
	{"type" : "geneshift", "description" : "Geneshift (2017)"}, 
	{"type" : "giantscitizenkabuto", "description" : "Giants: Citizen Kabuto (2000)"}, 
	{"type" : "globaloperations", "description" : "Global Operations (2002)"}, 
	{"type" : "ges", "description" : "GoldenEye: Source (2010)"}, 
	{"type" : "gore", "description" : "Gore: Ultimate Soldier (2002)"}, 
	{"type" : "fivem", "description" : "Grand Theft Auto V - FiveM (2013)"}, 
	{"type" : "mtasa", "description" : "Grand Theft Auto: San Andreas - Multi Theft Auto (2004)"}, 
	{"type" : "mtavc", "description" : "Grand Theft Auto: Vice City - Multi Theft Auto (2002)"}, 
	{"type" : "gunmanchronicles", "description" : "Gunman Chronicles (2000)"}, 
	{"type" : "hl2dm", "description" : "Half-Life 2: Deathmatch (2004)"}, 
	{"type" : "hldm", "description" : "Half-Life Deathmatch (1998)"}, 
	{"type" : "hldms", "description" : "Half-Life Deathmatch: Source (2005)"}, 
	{"type" : "halo", "description" : "Halo (2003)"}, 
	{"type" : "halo2", "description" : "Halo 2 (2007)"}, 
	{"type" : "hll", "description" : "Hell Let Loose"}, 
	{"type" : "heretic2", "description" : "Heretic II (1998)"}, 
	{"type" : "hexen2", "description" : "Hexen II (1997)"}, 
	{"type" : "had2", "description" : "Hidden & Dangerous 2 (2003)"}, 
	{"type" : "homefront", "description" : "Homefront (2011)"}, 
	{"type" : "homeworld2", "description" : "Homeworld 2 (2003)"}, 
	{"type" : "hurtworld", "description" : "Hurtworld (2015)"}, 
	{"type" : "igi2", "description" : "I.G.I.-2: Covert Strike (2003)"}, 
	{"type" : "il2", "description" : "IL-2 Sturmovik (2001)"}, 
	{"type" : "insurgency", "description" : "Insurgency (2014)"}, 
	{"type" : "insurgencysandstorm", "description" : "Insurgency: Sandstorm (2018)"}, 
	{"type" : "ironstorm", "description" : "Iron Storm (2002)"}, 
	{"type" : "jamesbondnightfire", "description" : "James Bond 007: Nightfire (2002)"}, 
	{"type" : "jc2mp", "description" : "Just Cause 2 - Multiplayer (2010)"}, 
	{"type" : "jc3mp", "description" : "Just Cause 3 - Multiplayer (2017)"}, 
	{"type" : "kspdmp", "description" : "Kerbal Space Program - DMP Multiplayer (2015)"}, 
	{"type" : "killingfloor", "description" : "Killing Floor (2009)"}, 
	{"type" : "killingfloor2", "description" : "Killing Floor 2 (2016)"}, 
	{"type" : "kingpin", "description" : "Kingpin: Life of Crime (1999)"}, 
	{"type" : "kisspc", "description" : "Kiss: Psycho Circus: The Nightmare Child (2000)"}, 
	{"type" : "kzmod", "description" : "Kreedz Climbing (2017)"}, 
	{"type" : "left4dead", "description" : "Left 4 Dead (2008)"}, 
	{"type" : "left4dead2", "description" : "Left 4 Dead 2 (2009)"}, 
	{"type" : "m2mp", "description" : "Mafia II - Multiplayer (2010)"}, 
	{"type" : "m2o", "description" : "Mafia II - Online (2010)"}, 
	{"type" : "moh2010", "description" : "Medal of Honor (2010)"}, 
	{"type" : "mohab", "description" : "Medal of Honor: Airborne (2007)"}, 
	{"type" : "mohaa", "description" : "Medal of Honor: Allied Assault (2002)"}, 
	{"type" : "mohbt", "description" : "Medal of Honor: Allied Assault Breakthrough (2003)"}, 
	{"type" : "mohsh", "description" : "Medal of Honor: Allied Assault Spearhead (2002)"}, 
	{"type" : "mohpa", "description" : "Medal of Honor: Pacific Assault (2004)"}, 
	{"type" : "mohwf", "description" : "Medal of Honor: Warfighter (2012)"}, 
	{"type" : "medievalengineers", "description" : "Medieval Engineers (2015)"}, 
	{"type" : "minecraftping", "description" : "Minecraft ping (2009)"}, 
	{"type" : "minecraft", "description" : "Minecraft (2009)"}, 
	{"type" : "minecraftbe", "description" : "Minecraft: Bedrock Edition (2011)"}, 
	{"type" : "minecraftpe", "description" : "Minecraft: Pocket Edition (2011)"}, 
	{"type" : "mnc", "description" : "Monday Night Combat (2011)"}, 
	{"type" : "mordhau", "description" : "Mordhau (2019)"}, 
	{"type" : "mumble", "description" : "Mumble - GTmurmur Plugin (2005)"}, 
	{"type" : "mumbleping", "description" : "Mumble - Lightweight (2005)"}, 
	{"type" : "nascarthunder2004", "description" : "NASCAR Thunder 2004 (2003)"}, 
	{"type" : "ns", "description" : "Natural Selection (2002)"}, 
	{"type" : "ns2", "description" : "Natural Selection 2 (2012)"}, 
	{"type" : "nfshp2", "description" : "Need for Speed: Hot Pursuit 2 (2002)"}, 
	{"type" : "nab", "description" : "Nerf Arena Blast (1999)"}, 
	{"type" : "netpanzer", "description" : "netPanzer (2002)"}, 
	{"type" : "nwn", "description" : "Neverwinter Nights (2002)"}, 
	{"type" : "nwn2", "description" : "Neverwinter Nights 2 (2006)"}, 
	{"type" : "nexuiz", "description" : "Nexuiz (2005)"}, 
	{"type" : "nitrofamily", "description" : "Nitro Family (2004)"}, 
	{"type" : "nmrih", "description" : "No More Room in Hell (2011)"}, 
	{"type" : "nolf2", "description" : "No One Lives Forever 2: A Spy in H.A.R.M.\\\'s Way (2002)"}, 
	{"type" : "nucleardawn", "description" : "Nuclear Dawn (2011)"}, 
	{"type" : "openarena", "description" : "OpenArena (2005)"}, 
	{"type" : "openttd", "description" : "OpenTTD (2004)"}, 
	{"type" : "operationflashpoint", "description" : "Operation Flashpoint: Cold War Crisis (2001)"}, 
	{"type" : "flashpoint", "description" : "Operation Flashpoint: Cold War Crisis (2001)"}, 
	{"type" : "flashpointresistance", "description" : "Operation Flashpoint: Resistance (2002)"}, 
	{"type" : "painkiller", "description" : "Painkiller"}, 
	{"type" : "pixark", "description" : "PixARK (2018)"}, 
	{"type" : "postal2", "description" : "Postal 2"}, 
	{"type" : "prey", "description" : "Prey"}, 
	{"type" : "primalcarnage", "description" : "Primal Carnage: Extinction"}, 
	{"type" : "prbf2", "description" : "Project Reality: Battlefield 2 (2005)"}, 
	{"type" : "quake1", "description" : "Quake 1: QuakeWorld (1996)"}, 
	{"type" : "quake2", "description" : "Quake 2 (1997)"}, 
	{"type" : "quake3", "description" : "Quake 3: Arena (1999)"}, 
	{"type" : "quake4", "description" : "Quake 4 (2005)"}, 
	{"type" : "quakelive", "description" : "Quake Live (2010)"}, 
	{"type" : "ragdollkungfu", "description" : "Rag Doll Kung Fu"}, 
	{"type" : "r6", "description" : "Rainbow Six"}, 
	{"type" : "r6roguespear", "description" : "Rainbow Six 2: Rogue Spear"}, 
	{"type" : "r6ravenshield", "description" : "Rainbow Six 3: Raven Shield"}, 
	{"type" : "rallisportchallenge", "description" : "RalliSport Challenge"}, 
	{"type" : "rallymasters", "description" : "Rally Masters"}, 
	{"type" : "redorchestra", "description" : "Red Orchestra"}, 
	{"type" : "redorchestra2", "description" : "Red Orchestra 2"}, 
	{"type" : "redorchestraost", "description" : "Red Orchestra: Ostfront 41-45"}, 
	{"type" : "redline", "description" : "Redline"}, 
	{"type" : "rtcw", "description" : "Return to Castle Wolfenstein"}, 
	{"type" : "rfactor", "description" : "rFactor"}, 
	{"type" : "ricochet", "description" : "Ricochet"}, 
	{"type" : "riseofnations", "description" : "Rise of Nations"}, 
	{"type" : "rs2", "description" : "Rising Storm 2: Vietnam"}, 
	{"type" : "rune", "description" : "Rune"}, 
	{"type" : "rust", "description" : "Rust"}, 
	{"type" : "stalker", "description" : "S.T.A.L.K.E.R."}, 
	{"type" : "samp", "description" : "San Andreas Multiplayer"}, 
	{"type" : "ss", "description" : "Serious Sam"}, 
	{"type" : "ss2", "description" : "Serious Sam 2"}, 
	{"type" : "shatteredhorizon", "description" : "Shattered Horizon"}, 
	{"type" : "shogo", "description" : "Shogo"}, 
	{"type" : "shootmania", "description" : "Shootmania"}, 
	{"type" : "sin", "description" : "SiN"}, 
	{"type" : "sinep", "description" : "SiN Episodes"}, 
	{"type" : "soldat", "description" : "Soldat"}, 
	{"type" : "sof", "description" : "Soldier of Fortune"}, 
	{"type" : "sof2", "description" : "Soldier of Fortune 2"}, 
	{"type" : "spaceengineers", "description" : "Space Engineers"}, 
	{"type" : "squad", "description" : "Squad"}, 
	{"type" : "stbc", "description" : "Star Trek: Bridge Commander"}, 
	{"type" : "stvef", "description" : "Star Trek: Voyager - Elite Force"}, 
	{"type" : "stvef2", "description" : "Star Trek: Voyager - Elite Force 2"}, 
	{"type" : "swjk2", "description" : "Star Wars Jedi Knight II: Jedi Outcast (2002)"}, 
	{"type" : "swjk", "description" : "Star Wars Jedi Knight: Jedi Academy (2003)"}, 
	{"type" : "swbf", "description" : "Star Wars: Battlefront"}, 
	{"type" : "swbf2", "description" : "Star Wars: Battlefront 2"}, 
	{"type" : "swrc", "description" : "Star Wars: Republic Commando"}, 
	{"type" : "starbound", "description" : "Starbound"}, 
	{"type" : "starmade", "description" : "StarMade"}, 
	{"type" : "starsiege", "description" : "Starsiege (2009)"}, 
	{"type" : "suicidesurvival", "description" : "Suicide Survival"}, 
	{"type" : "svencoop", "description" : "Sven Coop"}, 
	{"type" : "swat4", "description" : "SWAT 4"}, 
	{"type" : "synergy", "description" : "Synergy"}, 
	{"type" : "tacticalops", "description" : "Tactical Ops"}, 
	{"type" : "takeonhelicopters", "description" : "Take On Helicopters (2011)"}, 
	{"type" : "teamfactor", "description" : "Team Factor"}, 
	{"type" : "tf2", "description" : "Team Fortress 2"}, 
	{"type" : "tfc", "description" : "Team Fortress Classic"}, 
	{"type" : "teamspeak2", "description" : "Teamspeak 2"}, 
	{"type" : "teamspeak3", "description" : "Teamspeak 3"}, 
	{"type" : "terminus", "description" : "Terminus"}, 
	{"type" : "terraria", "description" : "Terraria (2011)"}, 
	{"type" : "tshock", "description" : "Terraria - TShock (2011)"}, 
	{"type" : "forrest", "description" : "The Forrest (2014)"}, 
	{"type" : "hidden", "description" : "The Hidden (2005)"}, 
	{"type" : "nolf", "description" : "The Operative: No One Lives Forever (2000)"}, 
	{"type" : "ship", "description" : "The Ship"}, 
	{"type" : "graw", "description" : "Tom Clancy\\\'s Ghost Recon Advanced Warfighter (2006)"}, 
	{"type" : "graw2", "description" : "Tom Clancy\\\'s Ghost Recon Advanced Warfighter 2 (2007)"}, 
	{"type" : "thps3", "description" : "Tony Hawk\\\'s Pro Skater 3"}, 
	{"type" : "thps4", "description" : "Tony Hawk\\\'s Pro Skater 4"}, 
	{"type" : "thu2", "description" : "Tony Hawk\\\'s Underground 2"}, 
	{"type" : "towerunite", "description" : "Tower Unite"}, 
	{"type" : "trackmania2", "description" : "Trackmania 2"}, 
	{"type" : "trackmaniaforever", "description" : "Trackmania Forever"}, 
	{"type" : "tremulous", "description" : "Tremulous"}, 
	{"type" : "tribes1", "description" : "Tribes 1: Starsiege"}, 
	{"type" : "tribesvengeance", "description" : "Tribes: Vengeance"}, 
	{"type" : "tron20", "description" : "Tron 2.0"}, 
	{"type" : "turok2", "description" : "Turok 2"}, 
	{"type" : "universalcombat", "description" : "Universal Combat"}, 
	{"type" : "unreal", "description" : "Unreal"}, 
	{"type" : "ut", "description" : "Unreal Tournament"}, 
	{"type" : "ut2003", "description" : "Unreal Tournament 2003"}, 
	{"type" : "ut2004", "description" : "Unreal Tournament 2004"}, 
	{"type" : "ut3", "description" : "Unreal Tournament 3"}, 
	{"type" : "unturned", "description" : "unturned"}, 
	{"type" : "urbanterror", "description" : "Urban Terror"}, 
	{"type" : "v8supercar", "description" : "V8 Supercar Challenge"}, 
	{"type" : "ventrilo", "description" : "Ventrilo"}, 
	{"type" : "vcmp", "description" : "Vice City Multiplayer"}, 
	{"type" : "vietcong", "description" : "Vietcong"}, 
	{"type" : "vietcong2", "description" : "Vietcong 2"}, 
	{"type" : "warsow", "description" : "Warsow"}, 
	{"type" : "wheeloftime", "description" : "Wheel of Time"}, 
	{"type" : "wolfenstein2009", "description" : "Wolfenstein 2009"}, 
	{"type" : "wolfensteinet", "description" : "Wolfenstein: Enemy Territory"}, 
	{"type" : "xpandrally", "description" : "Xpand Rally"}, 
	{"type" : "zombiemaster", "description" : "Zombie Master"}, 
	{"type" : "zps", "description" : "Zombie Panic: Source"}	
];

function insert(config) {
    db = new DBManager(
        config["db_hostname"],
        config["db_port"],
        config["db_name"],
        config["db_Username"],
        config["db_Password"]
    );
    
    db.connect();
    
    for (let i = 0; i < suported_game_types.length;i++) {
        db.connection.query("INSERT INTO games (type, name) VALUES ('" + suported_game_types[i]["type"] + "', '" + suported_game_types[i]["description"].trim() + "');" , function (error, results) {
            if (error) {
                Log.print("could not insert game (" + suported_game_types[i]["type"]  + ")  " + suported_game_types[i]["description"] + " to db.", 2, "DB Manager");
                Log.printError(error);
                return;
            };
    
            Log.print("inserted game " + suported_game_types[i]["description"] + ".");
        });
    };
    
    db.disconnect();
};

module.exports = {
	insert: insert
};